const PROVINCE_CODES = {
  "北京市": "110000",
  "天津市": "120000",
  "河北省": "130000",
  "山西省": "140000",
  "內蒙古自治區": "150000",
  "内蒙古自治区": "150000",
  "遼寧省": "210000",
  "辽宁省": "210000",
  "吉林省": "220000",
  "黑龍江省": "230000",
  "黑龙江省": "230000",
  "上海市": "310000",
  "江蘇省": "320000",
  "江苏省": "320000",
  "浙江省": "330000",
  "安徽省": "340000",
  "福建省": "350000",
  "江西省": "360000",
  "山東省": "370000",
  "山东省": "370000",
  "河南省": "410000",
  "湖北省": "420000",
  "湖南省": "430000",
  "廣東省": "440000",
  "广东省": "440000",
  "廣西壯族自治區": "450000",
  "广西壮族自治区": "450000",
  "海南省": "460000",
  "重慶市": "500000",
  "重庆市": "500000",
  "四川省": "510000",
  "貴州省": "520000",
  "贵州省": "520000",
  "雲南省": "530000",
  "云南省": "530000",
  "西藏自治區": "540000",
  "西藏自治区": "540000",
  "陝西省": "610000",
  "陕西省": "610000",
  "甘肅省": "620000",
  "甘肃省": "620000",
  "青海省": "630000",
  "寧夏回族自治區": "640000",
  "宁夏回族自治区": "640000",
  "新疆維吾爾自治區": "650000",
  "新疆维吾尔自治区": "650000",
};

const PLACE_TEMPLATES = {
  mainlandCity: { type: "boundary", label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
  municipality: { type: "boundary", label: "北京市", names: ["北京市"], style: "municipality" },
  sar: { type: "boundary", label: "香港", names: ["香港特别行政区"], style: "sar" },
  cityMarker: { type: "marker", label: "東京", coordinates: [139.6917, 35.6895], group: "japan" },
};

const BOUNDARY_PRESETS = {
  "上海市": { label: "上海市", names: ["上海市"], style: "municipality" },
  "香港": { label: "香港", names: ["香港特别行政区"], style: "sar" },
  "香港特別行政區": { label: "香港", names: ["香港特别行政区"], style: "sar" },
  "澳門": { label: "澳門", names: ["澳门特别行政区"], style: "sar" },
  "澳门": { label: "澳門", names: ["澳门特别行政区"], style: "sar" },
  "澳門特別行政區": { label: "澳門", names: ["澳门特别行政区"], style: "sar" },
  "北京市": { label: "北京市", names: ["北京市"], style: "municipality" },
  "天津市": { label: "天津市", names: ["天津市"], style: "municipality" },
  "重慶市": { label: "重慶市", names: ["重庆市"], style: "municipality" },
  "重庆市": { label: "重慶市", names: ["重庆市"], style: "municipality" },
  "廣州市": { label: "廣州市", names: ["广州市"], province: "廣東省" },
  "广州市": { label: "廣州市", names: ["广州市"], province: "廣東省" },
  "廣東省廣州市": { label: "廣州市", names: ["广州市"], province: "廣東省" },
  "深圳市": { label: "深圳市", names: ["深圳市"], province: "廣東省" },
  "廣東省深圳市": { label: "深圳市", names: ["深圳市"], province: "廣東省" },
  "珠海市": { label: "珠海市", names: ["珠海市"], province: "廣東省" },
  "廣東省珠海市": { label: "珠海市", names: ["珠海市"], province: "廣東省" },
  "清遠市": { label: "清遠市", names: ["清远市"], province: "廣東省" },
  "清远市": { label: "清遠市", names: ["清远市"], province: "廣東省" },
  "廣東省清遠市": { label: "清遠市", names: ["清远市"], province: "廣東省" },
  "福州市": { label: "福州市", names: ["福州市"], province: "福建省" },
  "福建省福州市": { label: "福州市", names: ["福州市"], province: "福建省" },
  "寧德市": { label: "寧德市", names: ["宁德市"], province: "福建省" },
  "宁德市": { label: "寧德市", names: ["宁德市"], province: "福建省" },
  "福建省寧德市": { label: "寧德市", names: ["宁德市"], province: "福建省" },
  "廈門市": { label: "廈門市", names: ["厦门市"], province: "福建省" },
  "厦门市": { label: "廈門市", names: ["厦门市"], province: "福建省" },
  "福建省廈門市": { label: "廈門市", names: ["厦门市"], province: "福建省" },
  "泉州市": { label: "泉州市", names: ["泉州市"], province: "福建省" },
  "福建省泉州市": { label: "泉州市", names: ["泉州市"], province: "福建省" },
  "棗莊市": { label: "棗莊市", names: ["枣庄市"], province: "山東省" },
  "枣庄市": { label: "棗莊市", names: ["枣庄市"], province: "山東省" },
  "山東省棗莊市": { label: "棗莊市", names: ["枣庄市"], province: "山東省" },
  "濟寧市": { label: "濟寧市", names: ["济宁市"], province: "山東省" },
  "济宁市": { label: "濟寧市", names: ["济宁市"], province: "山東省" },
  "山東省濟寧市": { label: "濟寧市", names: ["济宁市"], province: "山東省" },
  "新鄉市": { label: "新鄉市", names: ["新乡市"], province: "河南省" },
  "新乡市": { label: "新鄉市", names: ["新乡市"], province: "河南省" },
  "河南省新鄉市": { label: "新鄉市", names: ["新乡市"], province: "河南省" },
  "贛州市": { label: "贛州市", names: ["赣州市"], province: "江西省" },
  "赣州市": { label: "贛州市", names: ["赣州市"], province: "江西省" },
  "江西省贛州市": { label: "贛州市", names: ["赣州市"], province: "江西省" },
  "蘇州市": { label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
  "苏州市": { label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
  "江蘇省蘇州市": { label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
};

const MARKER_PRESETS = {
  "上海": { label: "上海", coordinates: [121.4737, 31.2304], group: "sar" },
  "上海市": { label: "上海", coordinates: [121.4737, 31.2304], group: "sar" },
  "香港": { label: "香港", coordinates: [114.1694, 22.3193], group: "sar" },
  "澳門": { label: "澳門", coordinates: [113.5439, 22.1987], group: "sar" },
  "澳门": { label: "澳門", coordinates: [113.5439, 22.1987], group: "sar" },
  "花蓮": { label: "花蓮", coordinates: [121.6044, 23.9872], group: "taiwan", labelOffset: [7, 8] },
  "花蓮縣": { label: "花蓮", coordinates: [121.6044, 23.9872], group: "taiwan", labelOffset: [7, 8] },
  "台湾花莲县": { label: "花蓮", coordinates: [121.6044, 23.9872], group: "taiwan", labelOffset: [7, 8] },
  "台灣花蓮縣": { label: "花蓮", coordinates: [121.6044, 23.9872], group: "taiwan", labelOffset: [7, 8] },
  "台北": { label: "台北", coordinates: [121.5654, 25.033], group: "taiwan", labelOffset: [8, -12] },
  "台北市": { label: "台北", coordinates: [121.5654, 25.033], group: "taiwan", labelOffset: [8, -12] },
  "臺北市": { label: "台北", coordinates: [121.5654, 25.033], group: "taiwan", labelOffset: [8, -12] },
  "台灣台北市": { label: "台北", coordinates: [121.5654, 25.033], group: "taiwan", labelOffset: [8, -12] },
  "新北": { label: "新北", coordinates: [121.4628, 25.0169], group: "taiwan", labelOffset: [-42, 6] },
  "新北市": { label: "新北", coordinates: [121.4628, 25.0169], group: "taiwan", labelOffset: [-42, 6] },
  "台灣新北市": { label: "新北", coordinates: [121.4628, 25.0169], group: "taiwan", labelOffset: [-42, 6] },
  "南投": { label: "南投", coordinates: [120.9876, 23.8388], group: "taiwan", labelOffset: [-42, -4] },
  "南投縣": { label: "南投", coordinates: [120.9876, 23.8388], group: "taiwan", labelOffset: [-42, -4] },
  "台灣南投縣": { label: "南投", coordinates: [120.9876, 23.8388], group: "taiwan", labelOffset: [-42, -4] },
  "釜山": { label: "釜山", coordinates: [129.0756, 35.1796], group: "korea" },
  "釜山廣域市": { label: "釜山", coordinates: [129.0756, 35.1796], group: "korea" },
  "韓國釜山廣域市": { label: "釜山", coordinates: [129.0756, 35.1796], group: "korea" },
  "首爾": { label: "首爾", coordinates: [126.978, 37.5665], group: "korea" },
  "首爾特別市": { label: "首爾", coordinates: [126.978, 37.5665], group: "korea" },
  "韓國首爾特別市": { label: "首爾", coordinates: [126.978, 37.5665], group: "korea" },
  "濟州": { label: "濟州", coordinates: [126.5312, 33.4996], group: "korea" },
  "濟州道": { label: "濟州", coordinates: [126.5312, 33.4996], group: "korea" },
  "韓國濟州道": { label: "濟州", coordinates: [126.5312, 33.4996], group: "korea" },
  "京都": { label: "京都", coordinates: [135.7681, 35.0116], group: "japan", labelOffset: [-34, -14] },
  "京都市": { label: "京都", coordinates: [135.7681, 35.0116], group: "japan", labelOffset: [-34, -14] },
  "日本京都府京都市": { label: "京都", coordinates: [135.7681, 35.0116], group: "japan", labelOffset: [-34, -14] },
  "大津": { label: "大津", coordinates: [135.8546, 35.0179], group: "japan", labelOffset: [8, -12] },
  "大津市": { label: "大津", coordinates: [135.8546, 35.0179], group: "japan", labelOffset: [8, -12] },
  "日本滋賀縣大津市": { label: "大津", coordinates: [135.8546, 35.0179], group: "japan", labelOffset: [8, -12] },
  "名古屋": { label: "名古屋", coordinates: [136.9066, 35.1815], group: "japan", labelOffset: [8, 4] },
  "名古屋市": { label: "名古屋", coordinates: [136.9066, 35.1815], group: "japan", labelOffset: [8, 4] },
  "日本名古屋市": { label: "名古屋", coordinates: [136.9066, 35.1815], group: "japan", labelOffset: [8, 4] },
  "大阪": { label: "大阪", coordinates: [135.5023, 34.6937], group: "japan", labelOffset: [-34, 12] },
  "大阪市": { label: "大阪", coordinates: [135.5023, 34.6937], group: "japan", labelOffset: [-34, 12] },
  "日本大阪府大阪市": { label: "大阪", coordinates: [135.5023, 34.6937], group: "japan", labelOffset: [-34, 12] },
  "東京": { label: "東京", coordinates: [139.6917, 35.6895], group: "japan" },
  "東京都": { label: "東京", coordinates: [139.6917, 35.6895], group: "japan" },
  "日本東京都": { label: "東京", coordinates: [139.6917, 35.6895], group: "japan" },
  "奈良": { label: "奈良", coordinates: [135.8048, 34.6851], group: "japan", labelOffset: [8, 10] },
  "奈良市": { label: "奈良", coordinates: [135.8048, 34.6851], group: "japan", labelOffset: [8, 10] },
};

// Add new trips here.
// - type: "boundary" highlights a China mainland/SAR administrative region.
//   For ordinary prefecture-level cities, add province, e.g.
//   { type: "boundary", label: "蘇州市", names: ["苏州市"], province: "江蘇省" }
// - type: "marker" places an exact point on the interactive map.
//   coordinates are [longitude, latitude].
//   Optional labelOffset is [x, y] pixels for crowded clusters.
const VISITED_PLACES = [
  { type: "boundary", label: "上海市", names: ["上海市"], style: "municipality" },
  { type: "boundary", label: "香港", names: ["香港特别行政区"], style: "sar" },
  { type: "boundary", label: "澳門", names: ["澳门特别行政区"], style: "sar" },
  { type: "boundary", label: "廣州市", names: ["广州市"], province: "廣東省" },
  { type: "boundary", label: "深圳市", names: ["深圳市"], province: "廣東省" },
  { type: "boundary", label: "珠海市", names: ["珠海市"], province: "廣東省" },
  { type: "boundary", label: "清遠市", names: ["清远市"], province: "廣東省" },
  { type: "boundary", label: "重慶市", names: ["重庆市"], style: "municipality" },
  { type: "boundary", label: "北京市", names: ["北京市"], style: "municipality" },
  { type: "boundary", label: "福州市", names: ["福州市"], province: "福建省" },
  { type: "boundary", label: "寧德市", names: ["宁德市"], province: "福建省" },
  { type: "boundary", label: "廈門市", names: ["厦门市"], province: "福建省" },
  { type: "boundary", label: "泉州市", names: ["泉州市"], province: "福建省" },
  { type: "boundary", label: "棗莊市", names: ["枣庄市"], province: "山東省" },
  { type: "boundary", label: "濟寧市", names: ["济宁市"], province: "山東省" },
  { type: "boundary", label: "新鄉市", names: ["新乡市"], province: "河南省" },
  { type: "boundary", label: "贛州市", names: ["赣州市"], province: "江西省" },
  { type: "marker", label: "上海", coordinates: [121.4737, 31.2304], group: "sar" },
  { type: "marker", label: "香港", coordinates: [114.1694, 22.3193], group: "sar" },
  { type: "marker", label: "澳門", coordinates: [113.5439, 22.1987], group: "sar" },
  { type: "marker", label: "花蓮", coordinates: [121.6044, 23.9872], group: "taiwan", labelOffset: [7, 8] },
  { type: "marker", label: "台北", coordinates: [121.5654, 25.033], group: "taiwan", labelOffset: [8, -12] },
  { type: "marker", label: "新北", coordinates: [121.4628, 25.0169], group: "taiwan", labelOffset: [-42, 6] },
  { type: "marker", label: "南投", coordinates: [120.9876, 23.8388], group: "taiwan", labelOffset: [-42, -4] },
  { type: "marker", label: "釜山", coordinates: [129.0756, 35.1796], group: "korea" },
  { type: "marker", label: "首爾", coordinates: [126.978, 37.5665], group: "korea" },
  { type: "marker", label: "濟州", coordinates: [126.5312, 33.4996], group: "korea" },
  { type: "marker", label: "京都", coordinates: [135.7681, 35.0116], group: "japan", labelOffset: [-34, -14] },
  { type: "marker", label: "大津", coordinates: [135.8546, 35.0179], group: "japan", labelOffset: [8, -12] },
  { type: "marker", label: "名古屋", coordinates: [136.9066, 35.1815], group: "japan", labelOffset: [8, 4] },
  { type: "marker", label: "大阪", coordinates: [135.5023, 34.6937], group: "japan", labelOffset: [-34, 12] },
];

const SUMMARY_GROUPS = [
  { key: "boundary", title: "Mainland / SAR" },
  { key: "taiwan", title: "Taiwan" },
  { key: "korea", title: "Korea" },
  { key: "japan", title: "Japan" },
];

window.TRAVEL_MAP_DATA = {
  PROVINCE_CODES,
  PLACE_TEMPLATES,
  BOUNDARY_PRESETS,
  MARKER_PRESETS,
  VISITED_PLACES,
  SUMMARY_GROUPS,
};
