const PROVINCE_CODES = {
  "北京市": "110000",
  "天津市": "120000",
  "河北省": "130000",
  "山西省": "140000",
  "內蒙古自治區": "150000",
  "内蒙古自治区": "150000",
  "遼寧省": "210000",
  "辽宁省": "210000",
  "吉林省": "220000",
  "黑龍江省": "230000",
  "黑龙江省": "230000",
  "上海市": "310000",
  "江蘇省": "320000",
  "江苏省": "320000",
  "浙江省": "330000",
  "安徽省": "340000",
  "福建省": "350000",
  "江西省": "360000",
  "山東省": "370000",
  "山东省": "370000",
  "河南省": "410000",
  "湖北省": "420000",
  "湖南省": "430000",
  "廣東省": "440000",
  "广东省": "440000",
  "廣西壯族自治區": "450000",
  "广西壮族自治区": "450000",
  "海南省": "460000",
  "重慶市": "500000",
  "重庆市": "500000",
  "四川省": "510000",
  "貴州省": "520000",
  "贵州省": "520000",
  "雲南省": "530000",
  "云南省": "530000",
  "西藏自治區": "540000",
  "西藏自治区": "540000",
  "陝西省": "610000",
  "陕西省": "610000",
  "甘肅省": "620000",
  "甘肃省": "620000",
  "青海省": "630000",
  "寧夏回族自治區": "640000",
  "宁夏回族自治区": "640000",
  "新疆維吾爾自治區": "650000",
  "新疆维吾尔自治区": "650000",
};

const PLACE_TEMPLATES = {
  mainlandCity: { type: "boundary", label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
  municipality: { type: "boundary", label: "北京市", names: ["北京市"], style: "municipality" },
  sar: { type: "boundary", label: "香港", names: ["香港特别行政区"], style: "sar" },
  localBoundary: { type: "boundary", label: "京都市", names: ["京都市"], source: "local", group: "japan" },
};

const BOUNDARY_PRESETS = {
  "上海市": { label: "上海市", names: ["上海市"], style: "municipality" },
  "香港": { label: "香港", names: ["香港特别行政区"], style: "sar" },
  "香港特別行政區": { label: "香港", names: ["香港特别行政区"], style: "sar" },
  "澳門": { label: "澳門", names: ["澳门特别行政区"], style: "sar" },
  "澳门": { label: "澳門", names: ["澳门特别行政区"], style: "sar" },
  "澳門特別行政區": { label: "澳門", names: ["澳门特别行政区"], style: "sar" },
  "北京市": { label: "北京市", names: ["北京市"], style: "municipality" },
  "天津市": { label: "天津市", names: ["天津市"], style: "municipality" },
  "重慶市": { label: "重慶市", names: ["重庆市"], style: "municipality" },
  "重庆市": { label: "重慶市", names: ["重庆市"], style: "municipality" },
  "廣州市": { label: "廣州市", names: ["广州市"], province: "廣東省" },
  "广州市": { label: "廣州市", names: ["广州市"], province: "廣東省" },
  "廣東省廣州市": { label: "廣州市", names: ["广州市"], province: "廣東省" },
  "深圳市": { label: "深圳市", names: ["深圳市"], province: "廣東省" },
  "廣東省深圳市": { label: "深圳市", names: ["深圳市"], province: "廣東省" },
  "珠海市": { label: "珠海市", names: ["珠海市"], province: "廣東省" },
  "廣東省珠海市": { label: "珠海市", names: ["珠海市"], province: "廣東省" },
  "清遠市": { label: "清遠市", names: ["清远市"], province: "廣東省" },
  "清远市": { label: "清遠市", names: ["清远市"], province: "廣東省" },
  "廣東省清遠市": { label: "清遠市", names: ["清远市"], province: "廣東省" },
  "福州市": { label: "福州市", names: ["福州市"], province: "福建省" },
  "福建省福州市": { label: "福州市", names: ["福州市"], province: "福建省" },
  "寧德市": { label: "寧德市", names: ["宁德市"], province: "福建省" },
  "宁德市": { label: "寧德市", names: ["宁德市"], province: "福建省" },
  "福建省寧德市": { label: "寧德市", names: ["宁德市"], province: "福建省" },
  "廈門市": { label: "廈門市", names: ["厦门市"], province: "福建省" },
  "厦门市": { label: "廈門市", names: ["厦门市"], province: "福建省" },
  "福建省廈門市": { label: "廈門市", names: ["厦门市"], province: "福建省" },
  "泉州市": { label: "泉州市", names: ["泉州市"], province: "福建省" },
  "福建省泉州市": { label: "泉州市", names: ["泉州市"], province: "福建省" },
  "棗莊市": { label: "棗莊市", names: ["枣庄市"], province: "山東省" },
  "枣庄市": { label: "棗莊市", names: ["枣庄市"], province: "山東省" },
  "山東省棗莊市": { label: "棗莊市", names: ["枣庄市"], province: "山東省" },
  "濟寧市": { label: "濟寧市", names: ["济宁市"], province: "山東省" },
  "济宁市": { label: "濟寧市", names: ["济宁市"], province: "山東省" },
  "山東省濟寧市": { label: "濟寧市", names: ["济宁市"], province: "山東省" },
  "新鄉市": { label: "新鄉市", names: ["新乡市"], province: "河南省" },
  "新乡市": { label: "新鄉市", names: ["新乡市"], province: "河南省" },
  "河南省新鄉市": { label: "新鄉市", names: ["新乡市"], province: "河南省" },
  "贛州市": { label: "贛州市", names: ["赣州市"], province: "江西省" },
  "赣州市": { label: "贛州市", names: ["赣州市"], province: "江西省" },
  "江西省贛州市": { label: "贛州市", names: ["赣州市"], province: "江西省" },
  "蘇州市": { label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
  "苏州市": { label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
  "江蘇省蘇州市": { label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
  "花蓮": { label: "花蓮縣", names: ["花蓮縣"], source: "local", group: "taiwan" },
  "花蓮縣": { label: "花蓮縣", names: ["花蓮縣"], source: "local", group: "taiwan" },
  "台灣花蓮縣": { label: "花蓮縣", names: ["花蓮縣"], source: "local", group: "taiwan" },
  "台北": { label: "台北市", names: ["臺北市"], source: "local", group: "taiwan" },
  "台北市": { label: "台北市", names: ["臺北市"], source: "local", group: "taiwan" },
  "臺北市": { label: "台北市", names: ["臺北市"], source: "local", group: "taiwan" },
  "台灣台北市": { label: "台北市", names: ["臺北市"], source: "local", group: "taiwan" },
  "新北": { label: "新北市", names: ["新北市"], source: "local", group: "taiwan" },
  "新北市": { label: "新北市", names: ["新北市"], source: "local", group: "taiwan" },
  "台灣新北市": { label: "新北市", names: ["新北市"], source: "local", group: "taiwan" },
  "南投": { label: "南投縣", names: ["南投縣"], source: "local", group: "taiwan" },
  "南投縣": { label: "南投縣", names: ["南投縣"], source: "local", group: "taiwan" },
  "台灣南投縣": { label: "南投縣", names: ["南投縣"], source: "local", group: "taiwan" },
  "釜山": { label: "釜山廣域市", names: ["부산광역시"], source: "local", group: "korea" },
  "釜山廣域市": { label: "釜山廣域市", names: ["부산광역시"], source: "local", group: "korea" },
  "韓國釜山廣域市": { label: "釜山廣域市", names: ["부산광역시"], source: "local", group: "korea" },
  "首爾": { label: "首爾特別市", names: ["서울특별시"], source: "local", group: "korea" },
  "首爾特別市": { label: "首爾特別市", names: ["서울특별시"], source: "local", group: "korea" },
  "韓國首爾特別市": { label: "首爾特別市", names: ["서울특별시"], source: "local", group: "korea" },
  "濟州": { label: "濟州道", names: ["제주특별자치도"], source: "local", group: "korea" },
  "濟州道": { label: "濟州道", names: ["제주특별자치도"], source: "local", group: "korea" },
  "韓國濟州道": { label: "濟州道", names: ["제주특별자치도"], source: "local", group: "korea" },
  "京都": { label: "京都市", names: ["京都市"], source: "local", group: "japan" },
  "京都市": { label: "京都市", names: ["京都市"], source: "local", group: "japan" },
  "日本京都府京都市": { label: "京都市", names: ["京都市"], source: "local", group: "japan" },
  "大津": { label: "大津市", names: ["大津市"], source: "local", group: "japan" },
  "大津市": { label: "大津市", names: ["大津市"], source: "local", group: "japan" },
  "日本滋賀縣大津市": { label: "大津市", names: ["大津市"], source: "local", group: "japan" },
  "名古屋": { label: "名古屋市", names: ["名古屋市"], source: "local", group: "japan" },
  "名古屋市": { label: "名古屋市", names: ["名古屋市"], source: "local", group: "japan" },
  "日本名古屋市": { label: "名古屋市", names: ["名古屋市"], source: "local", group: "japan" },
  "大阪": { label: "大阪市", names: ["大阪市"], source: "local", group: "japan" },
  "大阪市": { label: "大阪市", names: ["大阪市"], source: "local", group: "japan" },
  "日本大阪府大阪市": { label: "大阪市", names: ["大阪市"], source: "local", group: "japan" },
};

// Add new trips here.
// Every entry must match a feature name in data/visited-boundaries.geojson.
// - Mainland China and SAR entries use the Greater China color by default.
//   For ordinary prefecture-level cities, include province, e.g.
//   { type: "boundary", label: "蘇州市", names: ["苏州市"], province: "江蘇省" }
// - Taiwan/Korea/Japan entries use source: "local" plus group: "taiwan" | "korea" | "japan".
const VISITED_PLACES = [
  { type: "boundary", label: "上海市", names: ["上海市"], style: "municipality" },
  { type: "boundary", label: "重慶市", names: ["重庆市"], style: "municipality" },
  { type: "boundary", label: "北京市", names: ["北京市"], style: "municipality" },

  { type: "boundary", label: "香港", names: ["香港特别行政区"], style: "sar" },
  { type: "boundary", label: "澳門", names: ["澳门特别行政区"], style: "sar" },

  { type: "boundary", label: "蘇州市", names: ["苏州市"], province: "江蘇省" },
  { type: "boundary", label: "南京市", names: ["南京市"], province: "江蘇省" },

  { type: "boundary", label: "杭州市", names: ["杭州市"], province: "浙江省" },

  { type: "boundary", label: "廣州市", names: ["广州市"], province: "廣東省" },
  { type: "boundary", label: "深圳市", names: ["深圳市"], province: "廣東省" },
  { type: "boundary", label: "珠海市", names: ["珠海市"], province: "廣東省" },
  { type: "boundary", label: "清遠市", names: ["清远市"], province: "廣東省" },
  { type: "boundary", label: "中山市", names: ["中山市"], province: "廣東省" },
  { type: "boundary", label: "肇慶市", names: ["肇庆市"], province: "廣東省" },

  { type: "boundary", label: "福州市", names: ["福州市"], province: "福建省" },
  { type: "boundary", label: "寧德市", names: ["宁德市"], province: "福建省" },
  { type: "boundary", label: "廈門市", names: ["厦门市"], province: "福建省" },
  { type: "boundary", label: "泉州市", names: ["泉州市"], province: "福建省" },
  { type: "boundary", label: "南平市", names: ["南平市"], province: "福建省" },

  { type: "boundary", label: "棗莊市", names: ["枣庄市"], province: "山東省" },
  { type: "boundary", label: "濟寧市", names: ["济宁市"], province: "山東省" },

  { type: "boundary", label: "新鄉市", names: ["新乡市"], province: "河南省" },

  { type: "boundary", label: "贛州市", names: ["赣州市"], province: "江西省" },

  { type: "boundary", label: "花蓮縣", names: ["花蓮縣"], source: "local", group: "taiwan" },
  { type: "boundary", label: "台北市", names: ["臺北市"], source: "local", group: "taiwan" },
  { type: "boundary", label: "新北市", names: ["新北市"], source: "local", group: "taiwan" },
  { type: "boundary", label: "南投縣", names: ["南投縣"], source: "local", group: "taiwan" },

  { type: "boundary", label: "釜山廣域市", names: ["부산광역시"], source: "local", group: "korea" },
  { type: "boundary", label: "首爾特別市", names: ["서울특별시"], source: "local", group: "korea" },
  { type: "boundary", label: "濟州道", names: ["제주특별자치도"], source: "local", group: "korea" },
  { type: "boundary", label: "水原市", names: ["수원시"], source: "local", group: "korea" },

  { type: "boundary", label: "京都市", names: ["京都市"], source: "local", group: "japan" },
  { type: "boundary", label: "大津市", names: ["大津市"], source: "local", group: "japan" },
  { type: "boundary", label: "名古屋市", names: ["名古屋市"], source: "local", group: "japan" },
  { type: "boundary", label: "宇治市", names: ["宇治市"], source: "local", group: "japan" },
  { type: "boundary", label: "八幡市", names: ["八幡市"], source: "local", group: "japan" },
  { type: "boundary", label: "奈良市", names: ["奈良市"], source: "local", group: "japan" },
  { type: "boundary", label: "高山市", names: ["高山市"], source: "local", group: "japan" },
  { type: "boundary", label: "松江市", names: ["松江市"], source: "local", group: "japan" },
  { type: "boundary", label: "白川村", names: ["白川村"], source: "local", group: "japan" },
  { type: "boundary", label: "大阪市", names: ["大阪市"], source: "local", group: "japan" },
];

const SUMMARY_GROUPS = [
  { key: "boundary", title: "Mainland / SAR" },
  { key: "taiwan", title: "Taiwan" },
  { key: "korea", title: "Korea" },
  { key: "japan", title: "Japan" },
];

window.TRAVEL_MAP_DATA = {
  PROVINCE_CODES,
  PLACE_TEMPLATES,
  BOUNDARY_PRESETS,
  VISITED_PLACES,
  SUMMARY_GROUPS,
};
